### ISSUE TITLE
Default to query mode (no -q)

### ISSUE THREAD

**Issue by mterron** [varbhat/torpar#1]
I'd like to be able to just type `torpar "something I'd like to find"` to search instead of having to remember to add `-q`.

**Comment by varbhat** [comment]
@mterron , `torpar` uses [pflag](https://github.com/spf13/pflag) for handling flags. I think the feature you requested can't be implemented using `pflag` and that it involves fiddling with arguments manually.

What about using `alias`  ? It solves the exact problem you mentioned. You can alias torpar like this.

`alias tps='torpar -q'` 

Then, you can directly search without `-q` .


`tps SearchTerm`

**Comment by mterron** [comment]
The query is the first positional argument in my example. I have already aliased `torpar` but thought it might be more intuitive to support it by default :).

Thanks!

**Comment by varbhat** [comment]
@mterron i may implement this
