### ISSUE TITLE
Position and sorting by size

### ISSUE THREAD

**Issue by futurevessel** [varbhat/torpar#2]
Thanks for this great tool, a couple of possible features I'd like to request is having the application remember the torrent list position you were at when returning from having pressed enter to see torrent details, and also a way to sort torrents by size.

**Comment by varbhat** [comment]
@futurevessel , I will consider adding features you described.

Regarding sorting torrents by size, How should it be implemented **User Interface** wise ? Should we have seperate menu? Or will shortcuts suffice? Please share your opinion on this.

**Comment by futurevessel** [comment]
If the only sorting option is 'size' I would suggest 's', if you want to allow sorting by seeds and leeches as well, then I would suggest 's' for seeds, 'l' for leeches and 'z' for size.

Interface-wise I think key shortcuts should suffice since you provide the shortcut keys at the bottom at all times (which is excellent by the way)

Anyway, thanks for a great tool and for considering my requests, take care!

**Comment by varbhat** [comment]
@futurevessel  , Please see https://github.com/varbhat/torpar/commit/e6e183abfed2464c919332f27793c73082797b06 .

I fixed it to  retain Position of Search now.

I will also add sorting feature soon

**Comment by varbhat** [comment]
@futurevessel  , Please see https://github.com/varbhat/torpar/commit/b78f07490251471722c88fb2531cb07971ded02a .

It adds Sorting by Torrent Size .

Thus , I think both these issues are resolved .

I am closing this now. Feel free to re-open if you find any issues .
